/* Декларация интерфейса установки времени переключения состояний */

package traffic_light.ICSTimes

const UInt8 MaxTimesSize = 8;

typedef sequence<UInt8, MaxTimesSize> ArrayTimes;

interface {
    /* ICSTimes interface method */
    CSTimes(in ArrayTimes times, out UInt8 code);
}
