/* The following code has been generated by `einit` program */

#include <stdlib.h>
#include <stdio.h>

#include <rtl/retcode.h>
#include <coresrv/entity/entity_api.h>
#include <services/handle/if_connection.h>



static const EndpointInfo endpointsInfo_kl_VfsNet_0[12] = {
    {
        .name = "kl.Vfs.server",
        .riid = 0,
        .iface_name = "kl.VfsFilesystem",
    },
    {
        .name = "vfs.server",
        .riid = 0,
        .iface_name = "kl.VfsFilesystem",
    },
    {
        .name = "kl.Vfs.netcfg",
        .riid = 1,
        .iface_name = "kl.VfsNetConfig",
    },
    {
        .name = "vfs.netcfg",
        .riid = 1,
        .iface_name = "kl.VfsNetConfig",
    },
    {
        .name = "kl.Vfs.bpfcfg",
        .riid = 2,
        .iface_name = "kl.VfsBPFilter",
    },
    {
        .name = "vfs.bpfcfg",
        .riid = 2,
        .iface_name = "kl.VfsBPFilter",
    },
    {
        .name = "kl.Vfs.npfcfg",
        .riid = 3,
        .iface_name = "kl.VfsNPFilter",
    },
    {
        .name = "vfs.npfcfg",
        .riid = 3,
        .iface_name = "kl.VfsNPFilter",
    },
    {
        .name = "kl.Vfs.xattrcfg",
        .riid = 4,
        .iface_name = "kl.VfsExtAttr",
    },
    {
        .name = "vfs.xattrcfg",
        .riid = 4,
        .iface_name = "kl.VfsExtAttr",
    },
    {
        .name = "kl.Vfs.aclcfg",
        .riid = 5,
        .iface_name = "kl.VfsACL",
    },
    {
        .name = "vfs.aclcfg",
        .riid = 5,
        .iface_name = "kl.VfsACL",
    }
};
static const EntityInfo taskInfo_kl_VfsNet_0 = {
    .eiid = "kl.VfsNet",
    .max_endpoints = 12,
    .endpoints = endpointsInfo_kl_VfsNet_0,
};
static const EndpointInfo endpointsInfo_kl_VfsRamFs_1[12] = {
    {
        .name = "kl.Vfs.server",
        .riid = 0,
        .iface_name = "kl.VfsFilesystem",
    },
    {
        .name = "vfs.server",
        .riid = 0,
        .iface_name = "kl.VfsFilesystem",
    },
    {
        .name = "kl.Vfs.netcfg",
        .riid = 1,
        .iface_name = "kl.VfsNetConfig",
    },
    {
        .name = "vfs.netcfg",
        .riid = 1,
        .iface_name = "kl.VfsNetConfig",
    },
    {
        .name = "kl.Vfs.bpfcfg",
        .riid = 2,
        .iface_name = "kl.VfsBPFilter",
    },
    {
        .name = "vfs.bpfcfg",
        .riid = 2,
        .iface_name = "kl.VfsBPFilter",
    },
    {
        .name = "kl.Vfs.npfcfg",
        .riid = 3,
        .iface_name = "kl.VfsNPFilter",
    },
    {
        .name = "vfs.npfcfg",
        .riid = 3,
        .iface_name = "kl.VfsNPFilter",
    },
    {
        .name = "kl.Vfs.xattrcfg",
        .riid = 4,
        .iface_name = "kl.VfsExtAttr",
    },
    {
        .name = "vfs.xattrcfg",
        .riid = 4,
        .iface_name = "kl.VfsExtAttr",
    },
    {
        .name = "kl.Vfs.aclcfg",
        .riid = 5,
        .iface_name = "kl.VfsACL",
    },
    {
        .name = "vfs.aclcfg",
        .riid = 5,
        .iface_name = "kl.VfsACL",
    }
};
static const EntityInfo taskInfo_kl_VfsRamFs_1 = {
    .eiid = "kl.VfsRamFs",
    .max_endpoints = 12,
    .endpoints = endpointsInfo_kl_VfsRamFs_1,
};
static const EndpointInfo endpointsInfo_kl_drivers_BSP_2[2] = {
    {
        .name = "kl.drivers.BSP.bsp",
        .riid = 0,
        .iface_name = "kl.drivers.BSP",
    },
    {
        .name = "bsp",
        .riid = 0,
        .iface_name = "kl.drivers.BSP",
    }
};
static const EntityInfo taskInfo_kl_drivers_BSP_2 = {
    .eiid = "kl.drivers.BSP",
    .max_endpoints = 2,
    .endpoints = endpointsInfo_kl_drivers_BSP_2,
};
static const EndpointInfo endpointsInfo_kl_drivers_GPIO_3[4] = {
    {
        .name = "kl.drivers.GPIO.driver",
        .riid = 0,
        .iface_name = "kl.drivers.Driver",
    },
    {
        .name = "driver",
        .riid = 0,
        .iface_name = "kl.drivers.Driver",
    },
    {
        .name = "kl.drivers.GPIO.gpio",
        .riid = 1,
        .iface_name = "kl.drivers.GPIO",
    },
    {
        .name = "gpio",
        .riid = 1,
        .iface_name = "kl.drivers.GPIO",
    }
};
static const EntityInfo taskInfo_kl_drivers_GPIO_3 = {
    .eiid = "kl.drivers.GPIO",
    .max_endpoints = 4,
    .endpoints = endpointsInfo_kl_drivers_GPIO_3,
};
static const EndpointInfo endpointsInfo_kl_drivers_RAMDisk_4[2] = {
    {
        .name = "kl.drivers.RAMDisk.ramdisk",
        .riid = 0,
        .iface_name = "kl.drivers.Block",
    },
    {
        .name = "ramdisk",
        .riid = 0,
        .iface_name = "kl.drivers.Block",
    }
};
static const EntityInfo taskInfo_kl_drivers_RAMDisk_4 = {
    .eiid = "kl.drivers.RAMDisk",
    .max_endpoints = 2,
    .endpoints = endpointsInfo_kl_drivers_RAMDisk_4,
};
static const EndpointInfo endpointsInfo_kl_rump_Dhcpcd_5[2] = {
    {
        .name = "kl.rump.Dhcpcd.dhcpcd",
        .riid = 0,
        .iface_name = "kl.rump.DhcpcdConfig",
    },
    {
        .name = "dhcpcd",
        .riid = 0,
        .iface_name = "kl.rump.DhcpcdConfig",
    }
};
static const EntityInfo taskInfo_kl_rump_Dhcpcd_5 = {
    .eiid = "kl.rump.Dhcpcd",
    .max_endpoints = 2,
    .endpoints = endpointsInfo_kl_rump_Dhcpcd_5,
};
static const EntityInfo taskInfo_traffic_light_Communication_6 = {
    .eiid = "traffic_light.Communication",
    .max_endpoints = 0,
    .endpoints = NK_NULL,
};
static const EntityInfo taskInfo_traffic_light_ControlSystem_7 = {
    .eiid = "traffic_light.ControlSystem",
    .max_endpoints = 0,
    .endpoints = NK_NULL,
};
static const EndpointInfo endpointsInfo_traffic_light_Diagnostics_8[2] = {
    {
        .name = "traffic_light.CDmessage.dmessage",
        .riid = 0,
        .iface_name = "traffic_light.IDiagnostics",
    },
    {
        .name = "diagnostics.dmessage",
        .riid = 0,
        .iface_name = "traffic_light.IDiagnostics",
    }
};
static const EntityInfo taskInfo_traffic_light_Diagnostics_8 = {
    .eiid = "traffic_light.Diagnostics",
    .max_endpoints = 2,
    .endpoints = endpointsInfo_traffic_light_Diagnostics_8,
};
static const EndpointInfo endpointsInfo_traffic_light_LightsGPIO_9[2] = {
    {
        .name = "traffic_light.CMode.mode",
        .riid = 0,
        .iface_name = "traffic_light.IMode",
    },
    {
        .name = "lightsGpio.mode",
        .riid = 0,
        .iface_name = "traffic_light.IMode",
    }
};
static const EntityInfo taskInfo_traffic_light_LightsGPIO_9 = {
    .eiid = "traffic_light.LightsGPIO",
    .max_endpoints = 2,
    .endpoints = endpointsInfo_traffic_light_LightsGPIO_9,
};

/* init entity entry point */
int main(void) {

    Entity * task_kl_VfsNet_0;
    Entity * task_kl_VfsRamFs_1;
    Entity * task_kl_drivers_BSP_2;
    Entity * task_kl_drivers_GPIO_3;
    Entity * task_kl_drivers_RAMDisk_4;
    Entity * task_kl_rump_Dhcpcd_5;
    Entity * task_traffic_light_Communication_6;
    Entity * task_traffic_light_ControlSystem_7;
    Entity * task_traffic_light_Diagnostics_8;
    Entity * task_traffic_light_LightsGPIO_9;
    const char * taskInfo_kl_VfsNet_0_env[] = {
        "DEFAULT_DNS_SERVER=8.8.8.8",
        "VFS_FILESYSTEM_BACKEND=server:kl.VfsNet",
        "VFS_NETWORK_BACKEND=server:kl.VfsNet",
        RTL_NULL
    };
    const char * taskInfo_kl_VfsRamFs_1_env[] = {
        "ROOTFS=ramdisk0,0 / ext4 0",
        "VFS_FILESYSTEM_BACKEND=server:kl.VfsRamFs",
        RTL_NULL
    };



    const char * taskInfo_kl_rump_Dhcpcd_5_env[] = {
        "VFS_FILESYSTEM_BACKEND=client{fs->net}:kl.VfsRamFs",
        "VFS_NETWORK_BACKEND=client:kl.VfsNet",
        RTL_NULL
    };
    const char * taskInfo_traffic_light_Communication_6_env[] = {
        "MQTT_BROKER_ADDRESS=10.0.2.2",
        "MQTT_BROKER_PORT=1883",
        "VFS_FILESYSTEM_BACKEND=client:kl.VfsRamFs",
        "VFS_NETWORK_BACKEND=client:kl.VfsNet",
        RTL_NULL
    };
    const char * taskInfo_kl_VfsNet_0_args[] = {
        "VfsNet",
        "-l",
        "devfs /dev devfs 0",
        RTL_NULL
    };
    const char * taskInfo_kl_VfsRamFs_1_args[] = {
        "VfsRamFs",
        "-l",
        "devfs /dev devfs 0",
        RTL_NULL
    };
    const char * taskInfo_kl_drivers_BSP_2_args[] = {
        "bsp_hw",
        RTL_NULL
    };
    const char * taskInfo_kl_drivers_GPIO_3_args[] = {
        "gpio_hw",
        RTL_NULL
    };
    const char * taskInfo_kl_drivers_RAMDisk_4_args[] = {
        "ramdisk",
        RTL_NULL
    };
    const char * taskInfo_kl_rump_Dhcpcd_5_args[] = {
        "dhcpcd_entity",
        "-4",
        "-f",
        "/etc/dhcpcd.conf",
        RTL_NULL
    };
    const char * taskInfo_traffic_light_Communication_6_args[] = {
        "Communication",
        RTL_NULL
    };
    const char * taskInfo_traffic_light_ControlSystem_7_args[] = {
        "ControlSystem",
        RTL_NULL
    };
    const char * taskInfo_traffic_light_Diagnostics_8_args[] = {
        "Diagnostics",
        RTL_NULL
    };
    const char * taskInfo_traffic_light_LightsGPIO_9_args[] = {
        "LightsGPIO",
        RTL_NULL
    };

    /* initialize entities */

    task_traffic_light_Diagnostics_8 = EntityInitEx(
        &taskInfo_traffic_light_Diagnostics_8, "traffic_light.Diagnostics", "Diagnostics"
    );
    if (!task_traffic_light_Diagnostics_8) {
        fprintf(
            stderr, "Can't initialize task \"traffic_light.Diagnostics\"\n"
        );
        return EXIT_FAILURE;
    }

    if (EntitySetArgs(task_traffic_light_Diagnostics_8, taskInfo_traffic_light_Diagnostics_8_args) != rcOk) {
        fprintf(
            stderr, "Can't set args for task \"traffic_light.Diagnostics\"\n"
        );
        return EXIT_FAILURE;
    }
    task_traffic_light_LightsGPIO_9 = EntityInitEx(
        &taskInfo_traffic_light_LightsGPIO_9, "traffic_light.LightsGPIO", "LightsGPIO"
    );
    if (!task_traffic_light_LightsGPIO_9) {
        fprintf(
            stderr, "Can't initialize task \"traffic_light.LightsGPIO\"\n"
        );
        return EXIT_FAILURE;
    }

    if (EntitySetArgs(task_traffic_light_LightsGPIO_9, taskInfo_traffic_light_LightsGPIO_9_args) != rcOk) {
        fprintf(
            stderr, "Can't set args for task \"traffic_light.LightsGPIO\"\n"
        );
        return EXIT_FAILURE;
    }
    task_traffic_light_ControlSystem_7 = EntityInitEx(
        &taskInfo_traffic_light_ControlSystem_7, "traffic_light.ControlSystem", "ControlSystem"
    );
    if (!task_traffic_light_ControlSystem_7) {
        fprintf(
            stderr, "Can't initialize task \"traffic_light.ControlSystem\"\n"
        );
        return EXIT_FAILURE;
    }

    if (EntitySetArgs(task_traffic_light_ControlSystem_7, taskInfo_traffic_light_ControlSystem_7_args) != rcOk) {
        fprintf(
            stderr, "Can't set args for task \"traffic_light.ControlSystem\"\n"
        );
        return EXIT_FAILURE;
    }
    task_kl_drivers_RAMDisk_4 = EntityInitEx(
        &taskInfo_kl_drivers_RAMDisk_4, "kl.drivers.RAMDisk", "ramdisk"
    );
    if (!task_kl_drivers_RAMDisk_4) {
        fprintf(
            stderr, "Can't initialize task \"kl.drivers.RAMDisk\"\n"
        );
        return EXIT_FAILURE;
    }

    if (EntitySetArgs(task_kl_drivers_RAMDisk_4, taskInfo_kl_drivers_RAMDisk_4_args) != rcOk) {
        fprintf(
            stderr, "Can't set args for task \"kl.drivers.RAMDisk\"\n"
        );
        return EXIT_FAILURE;
    }
    task_kl_drivers_GPIO_3 = EntityInitEx(
        &taskInfo_kl_drivers_GPIO_3, "kl.drivers.GPIO", "gpio_hw"
    );
    if (!task_kl_drivers_GPIO_3) {
        fprintf(
            stderr, "Can't initialize task \"kl.drivers.GPIO\"\n"
        );
        return EXIT_FAILURE;
    }

    if (EntitySetArgs(task_kl_drivers_GPIO_3, taskInfo_kl_drivers_GPIO_3_args) != rcOk) {
        fprintf(
            stderr, "Can't set args for task \"kl.drivers.GPIO\"\n"
        );
        return EXIT_FAILURE;
    }
    task_kl_drivers_BSP_2 = EntityInitEx(
        &taskInfo_kl_drivers_BSP_2, "kl.drivers.BSP", "bsp_hw"
    );
    if (!task_kl_drivers_BSP_2) {
        fprintf(
            stderr, "Can't initialize task \"kl.drivers.BSP\"\n"
        );
        return EXIT_FAILURE;
    }

    if (EntitySetArgs(task_kl_drivers_BSP_2, taskInfo_kl_drivers_BSP_2_args) != rcOk) {
        fprintf(
            stderr, "Can't set args for task \"kl.drivers.BSP\"\n"
        );
        return EXIT_FAILURE;
    }
    task_kl_VfsRamFs_1 = EntityInitEx(
        &taskInfo_kl_VfsRamFs_1, "kl.VfsRamFs", "VfsRamFs"
    );
    if (!task_kl_VfsRamFs_1) {
        fprintf(
            stderr, "Can't initialize task \"kl.VfsRamFs\"\n"
        );
        return EXIT_FAILURE;
    }
    if (EntitySetEnv(task_kl_VfsRamFs_1, taskInfo_kl_VfsRamFs_1_env) != rcOk) {
        fprintf(
            stderr, "Can't set env for task \"kl.VfsRamFs\"\n"
        );
        return EXIT_FAILURE;
    }
    if (EntitySetArgs(task_kl_VfsRamFs_1, taskInfo_kl_VfsRamFs_1_args) != rcOk) {
        fprintf(
            stderr, "Can't set args for task \"kl.VfsRamFs\"\n"
        );
        return EXIT_FAILURE;
    }
    task_kl_VfsNet_0 = EntityInitEx(
        &taskInfo_kl_VfsNet_0, "kl.VfsNet", "VfsNet"
    );
    if (!task_kl_VfsNet_0) {
        fprintf(
            stderr, "Can't initialize task \"kl.VfsNet\"\n"
        );
        return EXIT_FAILURE;
    }
    if (EntitySetEnv(task_kl_VfsNet_0, taskInfo_kl_VfsNet_0_env) != rcOk) {
        fprintf(
            stderr, "Can't set env for task \"kl.VfsNet\"\n"
        );
        return EXIT_FAILURE;
    }
    if (EntitySetArgs(task_kl_VfsNet_0, taskInfo_kl_VfsNet_0_args) != rcOk) {
        fprintf(
            stderr, "Can't set args for task \"kl.VfsNet\"\n"
        );
        return EXIT_FAILURE;
    }
    task_kl_rump_Dhcpcd_5 = EntityInitEx(
        &taskInfo_kl_rump_Dhcpcd_5, "kl.rump.Dhcpcd", "dhcpcd_entity"
    );
    if (!task_kl_rump_Dhcpcd_5) {
        fprintf(
            stderr, "Can't initialize task \"kl.rump.Dhcpcd\"\n"
        );
        return EXIT_FAILURE;
    }
    if (EntitySetEnv(task_kl_rump_Dhcpcd_5, taskInfo_kl_rump_Dhcpcd_5_env) != rcOk) {
        fprintf(
            stderr, "Can't set env for task \"kl.rump.Dhcpcd\"\n"
        );
        return EXIT_FAILURE;
    }
    if (EntitySetArgs(task_kl_rump_Dhcpcd_5, taskInfo_kl_rump_Dhcpcd_5_args) != rcOk) {
        fprintf(
            stderr, "Can't set args for task \"kl.rump.Dhcpcd\"\n"
        );
        return EXIT_FAILURE;
    }
    task_traffic_light_Communication_6 = EntityInitEx(
        &taskInfo_traffic_light_Communication_6, "traffic_light.Communication", "Communication"
    );
    if (!task_traffic_light_Communication_6) {
        fprintf(
            stderr, "Can't initialize task \"traffic_light.Communication\"\n"
        );
        return EXIT_FAILURE;
    }
    if (EntitySetEnv(task_traffic_light_Communication_6, taskInfo_traffic_light_Communication_6_env) != rcOk) {
        fprintf(
            stderr, "Can't set env for task \"traffic_light.Communication\"\n"
        );
        return EXIT_FAILURE;
    }
    if (EntitySetArgs(task_traffic_light_Communication_6, taskInfo_traffic_light_Communication_6_args) != rcOk) {
        fprintf(
            stderr, "Can't set args for task \"traffic_light.Communication\"\n"
        );
        return EXIT_FAILURE;
    }

    /* setup connections between entities */

    if (EntityConnectToService(task_traffic_light_LightsGPIO_9, task_traffic_light_Diagnostics_8, "diagnostics_connection") != rcOk) {
        fprintf(stderr, "Can't setup a connection %s\n", "diagnostics_connection");
        return EXIT_FAILURE;
    }
    if (EntityConnectToService(task_traffic_light_ControlSystem_7, task_traffic_light_LightsGPIO_9, "lights_gpio_connection") != rcOk) {
        fprintf(stderr, "Can't setup a connection %s\n", "lights_gpio_connection");
        return EXIT_FAILURE;
    }



    if (EntityConnectToService(task_kl_VfsRamFs_1, task_kl_drivers_RAMDisk_4, "kl.drivers.RAMDisk") != rcOk) {
        fprintf(stderr, "Can't setup a connection %s\n", "kl.drivers.RAMDisk");
        return EXIT_FAILURE;
    }
    if (EntityConnectToService(task_kl_VfsNet_0, task_kl_drivers_BSP_2, "kl.drivers.BSP") != rcOk) {
        fprintf(stderr, "Can't setup a connection %s\n", "kl.drivers.BSP");
        return EXIT_FAILURE;
    }
    if (EntityConnectToService(task_kl_VfsNet_0, task_kl_drivers_GPIO_3, "kl.drivers.GPIO") != rcOk) {
        fprintf(stderr, "Can't setup a connection %s\n", "kl.drivers.GPIO");
        return EXIT_FAILURE;
    }
    if (EntityConnectToService(task_kl_rump_Dhcpcd_5, task_kl_VfsNet_0, "kl.VfsNet") != rcOk) {
        fprintf(stderr, "Can't setup a connection %s\n", "kl.VfsNet");
        return EXIT_FAILURE;
    }
    if (EntityConnectToService(task_kl_rump_Dhcpcd_5, task_kl_VfsRamFs_1, "kl.VfsRamFs") != rcOk) {
        fprintf(stderr, "Can't setup a connection %s\n", "kl.VfsRamFs");
        return EXIT_FAILURE;
    }
    if (EntityConnectToService(task_traffic_light_Communication_6, task_kl_VfsNet_0, "kl.VfsNet") != rcOk) {
        fprintf(stderr, "Can't setup a connection %s\n", "kl.VfsNet");
        return EXIT_FAILURE;
    }
    if (EntityConnectToService(task_traffic_light_Communication_6, task_kl_VfsRamFs_1, "kl.VfsRamFs") != rcOk) {
        fprintf(stderr, "Can't setup a connection %s\n", "kl.VfsRamFs");
        return EXIT_FAILURE;
    }



    /* run entities */

    if (EntityRun(task_traffic_light_Diagnostics_8) != rcOk) {
        fprintf(
            stderr, "Can't run task \"traffic_light.Diagnostics\"\n"
        );
        return EXIT_FAILURE;
    }
    if (EntityRun(task_traffic_light_LightsGPIO_9) != rcOk) {
        fprintf(
            stderr, "Can't run task \"traffic_light.LightsGPIO\"\n"
        );
        return EXIT_FAILURE;
    }
    if (EntityRun(task_traffic_light_ControlSystem_7) != rcOk) {
        fprintf(
            stderr, "Can't run task \"traffic_light.ControlSystem\"\n"
        );
        return EXIT_FAILURE;
    }
    if (EntityRun(task_kl_drivers_RAMDisk_4) != rcOk) {
        fprintf(
            stderr, "Can't run task \"kl.drivers.RAMDisk\"\n"
        );
        return EXIT_FAILURE;
    }
    if (EntityRun(task_kl_drivers_GPIO_3) != rcOk) {
        fprintf(
            stderr, "Can't run task \"kl.drivers.GPIO\"\n"
        );
        return EXIT_FAILURE;
    }
    if (EntityRun(task_kl_drivers_BSP_2) != rcOk) {
        fprintf(
            stderr, "Can't run task \"kl.drivers.BSP\"\n"
        );
        return EXIT_FAILURE;
    }
    if (EntityRun(task_kl_VfsRamFs_1) != rcOk) {
        fprintf(
            stderr, "Can't run task \"kl.VfsRamFs\"\n"
        );
        return EXIT_FAILURE;
    }
    if (EntityRun(task_kl_VfsNet_0) != rcOk) {
        fprintf(
            stderr, "Can't run task \"kl.VfsNet\"\n"
        );
        return EXIT_FAILURE;
    }
    if (EntityRun(task_kl_rump_Dhcpcd_5) != rcOk) {
        fprintf(
            stderr, "Can't run task \"kl.rump.Dhcpcd\"\n"
        );
        return EXIT_FAILURE;
    }
    if (EntityRun(task_traffic_light_Communication_6) != rcOk) {
        fprintf(
            stderr, "Can't run task \"traffic_light.Communication\"\n"
        );
        return EXIT_FAILURE;
    }


    return EXIT_SUCCESS;
}
